### ISSUE TITLE
Fails to build on 6.13

### ISSUE THREAD

**Issue by ionelmc** [draios/sysdig#2151]
From what I can tell the kernel version check was replaced with some a configure time check but it's broken and get the access_ok signature wrong. A regression of https://github.com/draios/sysdig/issues/1299
```
[165/171] Installing sysdig-0:0.40.1_rc2-1.x86_64                                                                                                                          100% |   7.2 MiB/s |  46.6 MiB |  00m06s
>>> Running post-install scriptlet: sysdig-0:0.40.1_rc2-1.x86_64
>>> Non-critical error in post-install scriptlet: sysdig-0:0.40.1_rc2-1.x86_64
>>> Scriptlet output:
>>> Creating symlink /var/lib/dkms/scap/8.0.0+driver/source -> /usr/src/scap-8.0.0+driver
>>> Sign command: /lib/modules/6.13.8-200.fc41.x86_64/build/scripts/sign-file
>>> Signing key: /var/lib/dkms/mok.key
>>> Public certificate (MOK): /var/lib/dkms/mok.pub
>>>
>>> Cleaning build area... done.
>>> Building module(s)...(bad exit status: 2)
>>> Failed command:
>>> make -j15 KERNELRELEASE=6.13.8-200.fc41.x86_64 -C /lib/modules/6.13.8-200.fc41.x86_64/build M=/var/lib/dkms/scap/8.0.0+driver/build
>>>
>>> Error! Bad return status for module build on kernel: 6.13.8-200.fc41.x86_64 (x86_64)
>>> Consult /var/lib/dkms/scap/8.0.0+driver/build/make.log for more information.
>>> Sign command: /lib/modules/6.13.8-200.fc41.x86_64/build/scripts/sign-file
>>> Signing key: /var/lib/dkms/mok.key
>>> Public certificate (MOK): /var/lib/dkms/mok.pub
>>>
>>> Cleaning build area... done.
>>> Building module(s)...(bad exit status: 2)
>>> Failed command:
>>> make -j15 KERNELRELEASE=6.13.8-200.fc41.x86_64 -C /lib/modules/6.13.8-200.fc41.x86_64/build M=/var/lib/dkms/scap/8.0.0+driver/build
>>>
>>> Error! Bad return status for module build on kernel: 6.13.8-200.fc41.x86_64 (x86_64)
>>> Consult /var/lib/dkms/scap/8.0.0+driver/build/make.log for more information.
>>>
>>> [RPM] %post(sysdig-0.40.1_rc2-1.x86_64) scriptlet failed, exit status 10
```

build logs

```
DKMS (dkms-3.1.6) make.log for scap/8.0.0+driver for kernel 6.13.8-200.fc41.x86_64 (x86_64)
Wed Mar 26 11:53:16 AM EET 2025

Cleaning build area
# command: make -C /lib/modules/6.13.8-200.fc41.x86_64/build M=/var/lib/dkms/scap/8.0.0+driver/build clean
make: Entering directory '/usr/src/kernels/6.13.8-200.fc41.x86_64'
make[1]: Entering directory '/var/lib/dkms/scap/8.0.0+driver/build'
make[1]: Leaving directory '/var/lib/dkms/scap/8.0.0+driver/build'
make: Leaving directory '/usr/src/kernels/6.13.8-200.fc41.x86_64'

# exit code: 0
# elapsed time: 00:00:00
----------------------------------------------------------------

Building module(s)
# command: make -j15 KERNELRELEASE=6.13.8-200.fc41.x86_64 -C /lib/modules/6.13.8-200.fc41.x86_64/build M=/var/lib/dkms/scap/8.0.0+driver/build
make: Entering directory '/usr/src/kernels/6.13.8-200.fc41.x86_64'
make[1]: Entering directory '/var/lib/dkms/scap/8.0.0+driver/build'
[configure-kmod] Including /var/lib/dkms/scap/8.0.0+driver/build//configure/DEVNODE_ARG1_CONST/Makefile.inc /var/lib/dkms/scap/8.0.0+driver/build//configure/ACCESS_OK_2/Makefile.inc /var/lib/dkms/scap/8.0.0+driver/build//configure/CLASS_CREATE_1/Makefile.inc
[configure-kmod] Build output for HAS_DEVNODE_ARG1_CONST:
[configure-kmod] make: Entering directory '/var/lib/dkms/scap/8.0.0+driver/build/configure/DEVNODE_ARG1_CONST' make -C /var/lib/dkms/scap/8.0.0+driver/build M=/var/lib/dkms/scap/8.0.0+driver/build/configure/DEVNODE_ARG1_CONST modules make[1]: Entering directory '/var/lib/dkms/scap/8.0.0+driver/build' make[1]: *** No rule to make target 'modules'.  Stop. make[1]: Leaving directory '/var/lib/dkms/scap/8.0.0+driver/build' make: *** [Makefile:15: all] Error 2 make: Leaving directory '/var/lib/dkms/scap/8.0.0+driver/build/configure/DEVNODE_ARG1_CONST'
[configure-kmod] Build output for HAS_ACCESS_OK_2:
[configure-kmod] make: Entering directory '/var/lib/dkms/scap/8.0.0+driver/build/configure/ACCESS_OK_2' make -C /var/lib/dkms/scap/8.0.0+driver/build M=/var/lib/dkms/scap/8.0.0+driver/build/configure/ACCESS_OK_2 modules make[1]: Entering directory '/var/lib/dkms/scap/8.0.0+driver/build' make[1]: *** No rule to make target 'modules'.  Stop. make[1]: Leaving directory '/var/lib/dkms/scap/8.0.0+driver/build' make: *** [Makefile:15: all] Error 2 make: Leaving directory '/var/lib/dkms/scap/8.0.0+driver/build/configure/ACCESS_OK_2'
[configure-kmod] Build output for HAS_CLASS_CREATE_1:
[configure-kmod] make: Entering directory '/var/lib/dkms/scap/8.0.0+driver/build/configure/CLASS_CREATE_1' make -C /var/lib/dkms/scap/8.0.0+driver/build M=/var/lib/dkms/scap/8.0.0+driver/build/configure/CLASS_CREATE_1 modules make[1]: Entering directory '/var/lib/dkms/scap/8.0.0+driver/build' make[1]: *** No rule to make target 'modules'.  Stop. make[1]: Leaving directory '/var/lib/dkms/scap/8.0.0+driver/build' make: *** [Makefile:15: all] Error 2 make: Leaving directory '/var/lib/dkms/scap/8.0.0+driver/build/configure/CLASS_CREATE_1'
  CC [M]  main.o
  CC [M]  dynamic_params_table.o
  CC [M]  fillers_table.o
  CC [M]  flags_table.o
  CC [M]  ppm_events.o
  CC [M]  ppm_fillers.o
  CC [M]  event_table.o
  CC [M]  syscall_table64.o
  CC [M]  ppm_cputime.o
  CC [M]  ppm_tp.o
  CC [M]  syscall_ia32_64_map.o
ppm_events.c: In function ‘ppm_copy_from_user’:
ppm_events.c:91:54: error: macro "access_ok" passed 3 arguments, but takes just 2
   91 |         if(likely(ppm_access_ok(VERIFY_READ, from, n)))
      |                                                      ^
In file included from /usr/src/kernels/6.13.8-200.fc41.x86_64/arch/x86/include/asm/uaccess.h:25,
                 from /usr/src/kernels/6.13.8-200.fc41.x86_64/include/linux/uaccess.h:12,
                 from /usr/src/kernels/6.13.8-200.fc41.x86_64/include/linux/sched/task.h:13,
                 from /usr/src/kernels/6.13.8-200.fc41.x86_64/include/linux/sched/signal.h:9,
                 from /usr/src/kernels/6.13.8-200.fc41.x86_64/include/linux/rcuwait.h:6,
                 from /usr/src/kernels/6.13.8-200.fc41.x86_64/include/linux/percpu-rwsem.h:7,
                 from /usr/src/kernels/6.13.8-200.fc41.x86_64/include/linux/fs.h:33,
                 from /usr/src/kernels/6.13.8-200.fc41.x86_64/include/linux/compat.h:17,
                 from ppm_events.c:13:
/usr/src/kernels/6.13.8-200.fc41.x86_64/include/asm-generic/access_ok.h:45:9: note: macro "access_ok" defined here
   45 | #define access_ok(addr, size) likely(__access_ok(addr, size))
      |         ^~~~~~~~~
In file included from /usr/src/kernels/6.13.8-200.fc41.x86_64/include/linux/export.h:5,
                 from /usr/src/kernels/6.13.8-200.fc41.x86_64/include/linux/linkage.h:7,
                 from /usr/src/kernels/6.13.8-200.fc41.x86_64/arch/x86/include/asm/cache.h:5,
                 from /usr/src/kernels/6.13.8-200.fc41.x86_64/include/linux/cache.h:6,
                 from /usr/src/kernels/6.13.8-200.fc41.x86_64/include/linux/time.h:5,
                 from /usr/src/kernels/6.13.8-200.fc41.x86_64/include/linux/compat.h:10:
ppm_events.c:50:41: error: ‘access_ok’ undeclared (first use in this function)
   50 | #define ppm_access_ok(type, addr, size) access_ok(type, addr, size)
      |                                         ^~~~~~~~~
/usr/src/kernels/6.13.8-200.fc41.x86_64/include/linux/compiler.h:76:45: note: in definition of macro ‘likely’
   76 | # define likely(x)      __builtin_expect(!!(x), 1)
      |                                             ^
ppm_events.c:91:19: note: in expansion of macro ‘ppm_access_ok’
   91 |         if(likely(ppm_access_ok(VERIFY_READ, from, n)))
      |                   ^~~~~~~~~~~~~
ppm_events.c:50:41: note: each undeclared identifier is reported only once for each function it appears in
   50 | #define ppm_access_ok(type, addr, size) access_ok(type, addr, size)
      |                                         ^~~~~~~~~
/usr/src/kernels/6.13.8-200.fc41.x86_64/include/linux/compiler.h:76:45: note: in definition of macro ‘likely’
   76 | # define likely(x)      __builtin_expect(!!(x), 1)
      |                                             ^
ppm_events.c:91:19: note: in expansion of macro ‘ppm_access_ok’
   91 |         if(likely(ppm_access_ok(VERIFY_READ, from, n)))
      |                   ^~~~~~~~~~~~~
ppm_events.c: In function ‘ppm_strncpy_from_user’:
ppm_events.c:127:67: error: macro "access_ok" passed 3 arguments, but takes just 2
  127 |                 if(!ppm_access_ok(VERIFY_READ, from, bytes_to_read)) {
      |                                                                   ^
/usr/src/kernels/6.13.8-200.fc41.x86_64/include/asm-generic/access_ok.h:45:9: note: macro "access_ok" defined here
   45 | #define access_ok(addr, size) likely(__access_ok(addr, size))
      |         ^~~~~~~~~
In file included from /usr/src/kernels/6.13.8-200.fc41.x86_64/include/linux/printk.h:6,
                 from /usr/src/kernels/6.13.8-200.fc41.x86_64/include/linux/kernel.h:31,
                 from /usr/src/kernels/6.13.8-200.fc41.x86_64/include/linux/cpumask.h:11,
                 from /usr/src/kernels/6.13.8-200.fc41.x86_64/include/linux/smp.h:13,
                 from /usr/src/kernels/6.13.8-200.fc41.x86_64/include/linux/tracepoint.h:15,
                 from /usr/src/kernels/6.13.8-200.fc41.x86_64/include/trace/syscall.h:5,
                 from main.c:14:
main.c: In function ‘scap_init’:
/usr/src/kernels/6.13.8-200.fc41.x86_64/include/linux/init.h:180:22: error: passing argument 1 of ‘class_create’ from incompatible pointer type [-Wincompatible-pointer-types]
  180 | #define THIS_MODULE (&__this_module)
      |                     ~^~~~~~~~~~~~~~~
      |                      |
      |                      struct module *
main.c:2893:36: note: in expansion of macro ‘THIS_MODULE’
 2893 |         g_ppm_class = class_create(THIS_MODULE, DRIVER_DEVICE_NAME);
      |                                    ^~~~~~~~~~~
In file included from /usr/src/kernels/6.13.8-200.fc41.x86_64/include/linux/device.h:31,
                 from /usr/src/kernels/6.13.8-200.fc41.x86_64/include/linux/node.h:18,
                 from /usr/src/kernels/6.13.8-200.fc41.x86_64/include/linux/cpu.h:17,
                 from /usr/src/kernels/6.13.8-200.fc41.x86_64/include/linux/static_call.h:135,
                 from /usr/src/kernels/6.13.8-200.fc41.x86_64/include/linux/tracepoint.h:22:
/usr/src/kernels/6.13.8-200.fc41.x86_64/include/linux/device/class.h:228:54: note: expected ‘const char *’ but argument is of type ‘struct module *’
  228 | struct class * __must_check class_create(const char *name);
      |                                          ~~~~~~~~~~~~^~~~
main.c:2893:23: error: too many arguments to function ‘class_create’
 2893 |         g_ppm_class = class_create(THIS_MODULE, DRIVER_DEVICE_NAME);
      |                       ^~~~~~~~~~~~
/usr/src/kernels/6.13.8-200.fc41.x86_64/include/linux/device/class.h:228:29: note: declared here
  228 | struct class * __must_check class_create(const char *name);
      |                             ^~~~~~~~~~~~
main.c:2904:30: error: assignment to ‘char * (*)(const struct device *, umode_t *)’ {aka ‘char * (*)(const struct device *, short unsigned int *)’} from incompatible pointer type ‘char * (*)(struct device *, umode_t *)’ {aka ‘char * (*)(struct device *, short unsigned int *)’} [-Wincompatible-pointer-types]
 2904 |         g_ppm_class->devnode = ppm_devnode;
      |                              ^
ppm_events.c:50:41: error: ‘access_ok’ undeclared (first use in this function)
   50 | #define ppm_access_ok(type, addr, size) access_ok(type, addr, size)
      |                                         ^~~~~~~~~
ppm_events.c:127:21: note: in expansion of macro ‘ppm_access_ok’
  127 |                 if(!ppm_access_ok(VERIFY_READ, from, bytes_to_read)) {
      |                     ^~~~~~~~~~~~~
make[3]: *** [/usr/src/kernels/6.13.8-200.fc41.x86_64/scripts/Makefile.build:196: main.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [/usr/src/kernels/6.13.8-200.fc41.x86_64/scripts/Makefile.build:196: ppm_events.o] Error 1
make[2]: *** [/usr/src/kernels/6.13.8-200.fc41.x86_64/Makefile:2029: .] Error 2
make[1]: *** [/usr/src/kernels/6.13.8-200.fc41.x86_64/Makefile:263: __sub-make] Error 2
make[1]: Leaving directory '/var/lib/dkms/scap/8.0.0+driver/build'
make: *** [Makefile:263: __sub-make] Error 2
make: Leaving directory '/usr/src/kernels/6.13.8-200.fc41.x86_64'

# exit code: 2
# elapsed time: 00:00:03
----------------------------------------------------------------
```

**Comment by hhoffstaette** [comment]
This is in falcosecurity-libs and fixed by commit https://github.com/falcosecurity/libs/commit/7f01ec89c565fcb45ade833b1312ae69637bc4ec

**Comment by russkel** [comment]
I am getting this error on the 6.14 kernel on Ubuntu 24.04. How do we go about fixing this?

**Comment by Sfinx** [comment]
After updating falcosecurity-libs to 0.21.0 it fails here:

```
/root/sysdig/userspace/sysdig/sysdig.cpp: In function ‘sysdig_init_res sysdig_init(int, char**)’:
/root/sysdig/userspace/sysdig/sysdig.cpp:1403:60: error: ‘class sinsp’ has no member named ‘set_print_container_data’
 1403 |                                                 inspector->set_print_container_data(true);
      |                                                            ^~~~~~~~~~~~~~~~~~~~~~~~
/root/sysdig/userspace/sysdig/sysdig.cpp:1413:60: error: ‘class sinsp’ has no member named ‘set_print_container_data’
 1413 |                                                 inspector->set_print_container_data(true);
      |                                                            ^~~~~~~~~~~~~~~~~~~~~~~~
/root/sysdig/userspace/sysdig/sysdig.cpp:1423:60: error: ‘class sinsp’ has no member named ‘set_print_container_data’
 1423 |                                                 inspector->set_print_container_data(true);
      |                                                            ^~~~~~~~~~~~~~~~~~~~~~~~
/root/sysdig/userspace/sysdig/sysdig.cpp:1585:60: error: ‘class sinsp’ has no member named ‘set_cri_timeout’; did you mean ‘set_thread_timeout_s’?
 1585 |                                                 inspector->set_cri_timeout(sinsp_numparser::parsed64(optarg));
      |                                                            ^~~~~~~~~~~~~~~
      |                                                            set_thread_timeout_s
/root/sysdig/userspace/sysdig/sysdig.cpp:1733:36: error: ‘class sinsp’ has no member named ‘set_cri_socket_path’
 1733 |                         inspector->set_cri_socket_path(cri_socket_path);
      |                                    ^~~~~~~~~~~~~~~~~~~
```

**Comment by Sfinx** [comment]
and in chisel_api.cpp too:

```
/root/sysdig/userspace/chisel/chisel_api.cpp: In static member function ‘static int lua_cbacks::get_container_table(lua_State*)’:
/root/sysdig/userspace/chisel/chisel_api.cpp:1133:15: error: ‘sinsp_container_manager’ does not name a type; did you mean ‘sinsp_plugin_manager’?
 1133 |         const sinsp_container_manager::map_ptr_t ctable = ch->m_inspector->m_container_manager.get_containers();
      |               ^~~~~~~~~~~~~~~~~~~~~~~
      |               sinsp_plugin_manager
/root/sysdig/userspace/chisel/chisel_api.cpp:1141:23: error: ‘ctable’ was not declared in this scope; did you mean ‘mutable’?
 1141 |         for(auto it = ctable->begin(); it != ctable->end(); ++it)
      |                       ^~~~~~
      |                       mutable
/root/sysdig/userspace/chisel/chisel_api.cpp:1157:22: error: ‘CT_DOCKER’ was not declared in this scope
 1157 |                 case CT_DOCKER:
      |                      ^~~~~~~~~
[configure-kmod] Setting HAS_ACCESS_OK_2 flag
/root/sysdig/userspace/chisel/chisel_api.cpp:1160:22: error: ‘CT_LXC’ was not declared in this scope
 1160 |                 case CT_LXC:
      |                      ^~~~~~
/root/sysdig/userspace/chisel/chisel_api.cpp:1163:22: error: ‘CT_LIBVIRT_LXC’ was not declared in this scope
 1163 |                 case CT_LIBVIRT_LXC:
      |                      ^~~~~~~~~~~~~~
/root/sysdig/userspace/chisel/chisel_api.cpp:1166:22: error: ‘CT_MESOS’ was not declared in this scope
 1166 |                 case CT_MESOS:
      |                      ^~~~~~~~
/root/sysdig/userspace/chisel/chisel_api.cpp:1169:22: error: ‘CT_RKT’ was not declared in this scope
 1169 |                 case CT_RKT:
      |                      ^~~~~~
/root/sysdig/userspace/chisel/chisel_api.cpp:1172:22: error: ‘CT_CRI’ was not declared in this scope
 1172 |                 case CT_CRI:
      |                      ^~~~~~
/root/sysdig/userspace/chisel/chisel_api.cpp:1175:22: error: ‘CT_CONTAINERD’ was not declared in this scope; did you mean ‘CO_CONTAINS’?
 1175 |                 case CT_CONTAINERD:
      |                      ^~~~~~~~~~~~~
      |                      CO_CONTAINS
/root/sysdig/userspace/chisel/chisel_api.cpp:1178:22: error: ‘CT_CRIO’ was not declared in this scope
 1178 |                 case CT_CRIO:
      |                      ^~~~~~~
[ 96%] Built target driver
/root/sysdig/userspace/chisel/chisel_api.cpp:1181:22: error: ‘CT_BPM’ was not declared in this scope
 1181 |                 case CT_BPM:
      |                      ^~~~~~
[ 96%] Building CXX object userspace/sysdig/CMakeFiles/sysdig.dir/__/chisel/chisel_fields_info.cpp.o
/root/sysdig/userspace/chisel/chisel_api.cpp:1184:22: error: ‘CT_PODMAN’ was not declared in this scope
 1184 |                 case CT_PODMAN:
      |                      ^~~~~~~~~
/root/sysdig/userspace/chisel/chisel_api.cpp:1123:23: warning: unused variable ‘ch’ [-Wunused-variable]
 1123 |         sinsp_chisel* ch = (sinsp_chisel*)lua_touserdata(ls, -1);
      |                       ^~
/root/sysdig/userspace/chisel/chisel_api.cpp: In static member function ‘static int lua_cbacks::is_print_container_data(lua_State*)’:
/root/sysdig/userspace/chisel/chisel_api.cpp:1214:46: error: ‘class sinsp’ has no member named ‘is_print_container_data’
 1214 |         lua_pushboolean(ls, ch->m_inspector->is_print_container_data());
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by apteryks** [comment]
I get similar errors, trying to build `sysdig` from the master branch or its latest `0.40.1` release with falcosecurity-libs 0.22.2. Here, with sysdig commit 034681784d1e8ff2b7b71d8a1d8a314f40f044f2:
```
cd /tmp/guix-build-sysdig-0.40.1.drv-0/build/userspace/sysdig && /gnu/store/wssvk5s5akbx78kx92bdkirrry87jvbj-gcc-14.3.0/bin/c++ -DCHISEL_TOOL_LIBRARY_NAME=\"sysdig\" -DHAS_CAPTURE -DHAS_MODERN_BPF -DPLATFORM_NAME=\"Linux\" -DSYSDIG_PROBE_BPF_FILEPATH=\".scap/scap-bpf.o\" -I/gnu/store/5c2a9vg2rb29nnk0lxrg7ybig2snjwy1-luajit-v2.1-0.04dca79/include/luajit-2.1 -I/tmp/guix-build-sysdig-0.40.1.drv-0/build/userspace/sinspui -I/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sysdig/../sinspui -I/tmp/guix-build-sysdig-0.40.1.drv-0/build/userspace/sysdig -I/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sysdig/. -I/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sysdig/../chisel -I/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sysdig/.. -I/tmp/guix-build-sysdig-0.40.1.drv-0/build/driver/src -isystem /gnu/store/cx68kqsajnd0rlcsis62kb7z3z711g56-falcosecurity-libs-0.22.2/lib/pkgconfig/../../include/falcosecurity -isystem /gnu/store/cx68kqsajnd0rlcsis62kb7z3z711g56-falcosecurity-libs-0.22.2/lib/pkgconfig/../../include/falcosecurity/libsinsp -isystem /gnu/store/cx68kqsajnd0rlcsis62kb7z3z711g56-falcosecurity-libs-0.22.2/lib/pkgconfig/../../include/falcosecurity/driver -isystem /gnu/store/bscmqd5a8r86bkpv4029q08slrb108dv-tbb-2021.6.0/include/tbb -isystem /gnu/store/cx68kqsajnd0rlcsis62kb7z3z711g56-falcosecurity-libs-0.22.2/lib/pkgconfig/../../include/falcosecurity/libscap -isystem /gnu/store/dhvpj54kh4zbsinp1wlp8zqlmp24s9z4-libelf-0.8.13/include/libelf -Wall -ggdb   -std=c++17 -O2 -g -DNDEBUG -std=c++17 -fdiagnostics-color=always -pthread -MD -MT userspace/sysdig/CMakeFiles/csysdig.dir/__/chisel/chisel_viewinfo.cpp.o -MF CMakeFiles/csysdig.dir/__/chisel/chisel_viewinfo.cpp.o.d -o CMakeFiles/csysdig.dir/__/chisel/chisel_viewinfo.cpp.o -c /tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_viewinfo.cpp
cd /tmp/guix-build-sysdig-0.40.1.drv-0/build/userspace/sysdig && /gnu/store/wssvk5s5akbx78kx92bdkirrry87jvbj-gcc-14.3.0/bin/c++ -DCHISEL_TOOL_LIBRARY_NAME=\"sysdig\" -DHAS_CAPTURE -DHAS_MODERN_BPF -DPLATFORM_NAME=\"Linux\" -DSYSDIG_PROBE_BPF_FILEPATH=\".scap/scap-bpf.o\" -I/gnu/store/5c2a9vg2rb29nnk0lxrg7ybig2snjwy1-luajit-v2.1-0.04dca79/include/luajit-2.1 -I/tmp/guix-build-sysdig-0.40.1.drv-0/build/userspace/sinspui -I/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sysdig/../sinspui -I/tmp/guix-build-sysdig-0.40.1.drv-0/build/userspace/sysdig -I/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sysdig/. -I/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sysdig/../chisel -I/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sysdig/.. -I/tmp/guix-build-sysdig-0.40.1.drv-0/build/driver/src -isystem /gnu/store/cx68kqsajnd0rlcsis62kb7z3z711g56-falcosecurity-libs-0.22.2/lib/pkgconfig/../../include/falcosecurity -isystem /gnu/store/cx68kqsajnd0rlcsis62kb7z3z711g56-falcosecurity-libs-0.22.2/lib/pkgconfig/../../include/falcosecurity/libsinsp -isystem /gnu/store/cx68kqsajnd0rlcsis62kb7z3z711g56-falcosecurity-libs-0.22.2/lib/pkgconfig/../../include/falcosecurity/driver -isystem /gnu/store/bscmqd5a8r86bkpv4029q08slrb108dv-tbb-2021.6.0/include/tbb -isystem /gnu/store/cx68kqsajnd0rlcsis62kb7z3z711g56-falcosecurity-libs-0.22.2/lib/pkgconfig/../../include/falcosecurity/libscap -isystem /gnu/store/dhvpj54kh4zbsinp1wlp8zqlmp24s9z4-libelf-0.8.13/include/libelf -Wall -ggdb   -std=c++17 -O2 -g -DNDEBUG -std=c++17 -fdiagnostics-color=always -pthread -MD -MT userspace/sysdig/CMakeFiles/csysdig.dir/__/chisel/chisel_table.cpp.o -MF CMakeFiles/csysdig.dir/__/chisel/chisel_table.cpp.o.d -o CMakeFiles/csysdig.dir/__/chisel/chisel_table.cpp.o -c /tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_table.cpp
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sysdig/sysdig.cpp: In function ‘captureinfo do_inspect(sinsp*, sinsp_cycledumper*, uint64_t, uint64_t, bool, bool, bool, bool, bool, std::unique_ptr<sinsp_filter>, std::vector<summary_table_entry>&, sinsp_evt_formatter*, sinsp_evt_formatter*)’:
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sysdig/sysdig.cpp:889:76: error: ‘const class sinsp_evt_param’ has no member named ‘m_val’
  889 |                                         uint16_t id = *(int16_t *)parinfo->m_val;
      |                                                                            ^~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sysdig/sysdig.cpp:895:76: error: ‘const class sinsp_evt_param’ has no member named ‘m_val’
  895 |                                         uint16_t id = *(int16_t *)parinfo->m_val;
      |                                                                            ^~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sysdig/sysdig.cpp: In function ‘sysdig_init_res sysdig_init(int, char**)’:
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sysdig/sysdig.cpp:1403:60: error: ‘class sinsp’ has no member named ‘set_print_container_data’
 1403 |                                                 inspector->set_print_container_data(true);
      |                                                            ^~~~~~~~~~~~~~~~~~~~~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sysdig/sysdig.cpp:1413:60: error: ‘class sinsp’ has no member named ‘set_print_container_data’
 1413 |                                                 inspector->set_print_container_data(true);
      |                                                            ^~~~~~~~~~~~~~~~~~~~~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sysdig/sysdig.cpp:1423:60: error: ‘class sinsp’ has no member named ‘set_print_container_data’
 1423 |                                                 inspector->set_print_container_data(true);
      |                                                            ^~~~~~~~~~~~~~~~~~~~~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sysdig/sysdig.cpp:1585:60: error: ‘class sinsp’ has no member named ‘set_cri_timeout’; did you mean ‘set_thread_timeout_s’?
 1585 |                                                 inspector->set_cri_timeout(sinsp_numparser::parsed64(optarg));
      |                                                            ^~~~~~~~~~~~~~~
      |                                                            set_thread_timeout_s
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sysdig/sysdig.cpp:1733:36: error: ‘class sinsp’ has no member named ‘set_cri_socket_path’
 1733 |                         inspector->set_cri_socket_path(cri_socket_path);
      |                                    ^~~~~~~~~~~~~~~~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sinspui/cursescomponents.cpp: In member function ‘const char* spy_text_renderer::process_event_spy(sinsp_evt*, int64_t*)’:
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sinspui/cursescomponents.cpp:138:36: error: ‘const class sinsp_evt_param’ has no member named ‘m_val’
  138 |         *len = *(int64_t*)parinfo->m_val;
      |                                    ^~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sinspui/cursescomponents.cpp: In member function ‘void curses_textbox::process_event_spy(sinsp_evt*, int32_t)’:
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sinspui/cursescomponents.cpp:928:55: error: ‘class sinsp’ has no member named ‘m_container_manager’; did you mean ‘m_plugin_manager’?
  928 |                 m_ctext->printf(" [%s]", m_inspector->m_container_manager.get_container_name(m_tinfo).c_str());
      |                                                       ^~~~~~~~~~~~~~~~~~~
      |                                                       m_plugin_manager
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp: In static member function ‘static int lua_cbacks::get_container_table(lua_State*)’:
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp:1133:15: error: ‘sinsp_container_manager’ does not name a type; did you mean ‘sinsp_plugin_manager’?
 1133 |         const sinsp_container_manager::map_ptr_t ctable = ch->m_inspector->m_container_manager.get_containers();
      |               ^~~~~~~~~~~~~~~~~~~~~~~
      |               sinsp_plugin_manager
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp:1141:23: error: ‘ctable’ was not declared in this scope; did you mean ‘mutable’?
 1141 |         for(auto it = ctable->begin(); it != ctable->end(); ++it)
      |                       ^~~~~~
      |                       mutable
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp:1157:22: error: ‘CT_DOCKER’ was not declared in this scope
 1157 |                 case CT_DOCKER:
      |                      ^~~~~~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp:1160:22: error: ‘CT_LXC’ was not declared in this scope
 1160 |                 case CT_LXC:
      |                      ^~~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp:1163:22: error: ‘CT_LIBVIRT_LXC’ was not declared in this scope
 1163 |                 case CT_LIBVIRT_LXC:
      |                      ^~~~~~~~~~~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sysdig/csysdig.cpp: In function ‘sysdig_init_res csysdig_init(int, char**)’:
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sysdig/csysdig.cpp:572:52: error: ‘class sinsp’ has no member named ‘set_print_container_data’
  572 |                                         inspector->set_print_container_data(true);
      |                                                    ^~~~~~~~~~~~~~~~~~~~~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sysdig/csysdig.cpp:640:60: error: ‘class sinsp’ has no member named ‘set_cri_timeout’; did you mean ‘set_thread_timeout_s’?
  640 |                                                 inspector->set_cri_timeout(sinsp_numparser::parsed64(optarg));
      |                                                            ^~~~~~~~~~~~~~~
      |                                                            set_thread_timeout_s
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sysdig/csysdig.cpp:705:36: error: ‘class sinsp’ has no member named ‘set_cri_socket_path’
  705 |                         inspector->set_cri_socket_path(cri_socket_path);
      |                                    ^~~~~~~~~~~~~~~~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp:1166:22: error: ‘CT_MESOS’ was not declared in this scope
 1166 |                 case CT_MESOS:
      |                      ^~~~~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp:1169:22: error: ‘CT_RKT’ was not declared in this scope
 1169 |                 case CT_RKT:
      |                      ^~~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp:1172:22: error: ‘CT_CRI’ was not declared in this scope
 1172 |                 case CT_CRI:
      |                      ^~~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp:1175:22: error: ‘CT_CONTAINERD’ was not declared in this scope; did you mean ‘CO_CONTAINS’?
 1175 |                 case CT_CONTAINERD:
      |                      ^~~~~~~~~~~~~
      |                      CO_CONTAINS
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp:1178:22: error: ‘CT_CRIO’ was not declared in this scope
 1178 |                 case CT_CRIO:
      |                      ^~~~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp:1181:22: error: ‘CT_BPM’ was not declared in this scope
 1181 |                 case CT_BPM:
      |                      ^~~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp:1184:22: error: ‘CT_PODMAN’ was not declared in this scope
 1184 |                 case CT_PODMAN:
      |                      ^~~~~~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp:1123:23: warning: unused variable ‘ch’ [-Wunused-variable]
 1123 |         sinsp_chisel* ch = (sinsp_chisel*)lua_touserdata(ls, -1);
      |                       ^~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp: In static member function ‘static int lua_cbacks::is_print_container_data(lua_State*)’:
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp:1214:46: error: ‘class sinsp’ has no member named ‘is_print_container_data’
 1214 |         lua_pushboolean(ls, ch->m_inspector->is_print_container_data());
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp: In static member function ‘static int lua_cbacks::get_container_table(lua_State*)’:
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp:1133:15: error: ‘sinsp_container_manager’ does not name a type; did you mean ‘sinsp_plugin_manager’?
 1133 |         const sinsp_container_manager::map_ptr_t ctable = ch->m_inspector->m_container_manager.get_containers();
      |               ^~~~~~~~~~~~~~~~~~~~~~~
      |               sinsp_plugin_manager
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp:1141:23: error: ‘ctable’ was not declared in this scope; did you mean ‘mutable’?
 1141 |         for(auto it = ctable->begin(); it != ctable->end(); ++it)
      |                       ^~~~~~
      |                       mutable
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp:1157:22: error: ‘CT_DOCKER’ was not declared in this scope
 1157 |                 case CT_DOCKER:
      |                      ^~~~~~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp:1160:22: error: ‘CT_LXC’ was not declared in this scope
 1160 |                 case CT_LXC:
      |                      ^~~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp:1163:22: error: ‘CT_LIBVIRT_LXC’ was not declared in this scope
 1163 |                 case CT_LIBVIRT_LXC:
      |                      ^~~~~~~~~~~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp:1166:22: error: ‘CT_MESOS’ was not declared in this scope
 1166 |                 case CT_MESOS:
      |                      ^~~~~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp:1169:22: error: ‘CT_RKT’ was not declared in this scope
 1169 |                 case CT_RKT:
      |                      ^~~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp:1172:22: error: ‘CT_CRI’ was not declared in this scope
 1172 |                 case CT_CRI:
      |                      ^~~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp:1175:22: error: ‘CT_CONTAINERD’ was not declared in this scope; did you mean ‘CO_CONTAINS’?
 1175 |                 case CT_CONTAINERD:
      |                      ^~~~~~~~~~~~~
      |                      CO_CONTAINS
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp:1178:22: error: ‘CT_CRIO’ was not declared in this scope
 1178 |                 case CT_CRIO:
      |                      ^~~~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp:1181:22: error: ‘CT_BPM’ was not declared in this scope
 1181 |                 case CT_BPM:
      |                      ^~~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sinspui/cursesui.cpp: In member function ‘void json_spy_renderer::process_event_spy(sinsp_evt*, int32_t)’:
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sinspui/cursesui.cpp:155:28: error: ‘class sinsp_threadinfo’ has no member named ‘m_container_id’; did you mean ‘get_container_id’?
  155 |                 if(!tinfo->m_container_id.empty())
      |                            ^~~~~~~~~~~~~~
      |                            get_container_id
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sinspui/cursesui.cpp:157:31: error: ‘sinsp_container_info’ does not name a type; did you mean ‘sinsp_menuitem_info’?
  157 |                         const sinsp_container_info::ptr_t container_info =
      |                               ^~~~~~~~~~~~~~~~~~~~
      |                               sinsp_menuitem_info
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp:1184:22: error: ‘CT_PODMAN’ was not declared in this scope
 1184 |                 case CT_PODMAN:
      |                      ^~~~~~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp:1123:23: warning: unused variable ‘ch’ [-Wunused-variable]
 1123 |         sinsp_chisel* ch = (sinsp_chisel*)lua_touserdata(ls, -1);
      |                       ^~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp: In static member function ‘static int lua_cbacks::is_print_container_data(lua_State*)’:
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/chisel/chisel_api.cpp:1214:46: error: ‘class sinsp’ has no member named ‘is_print_container_data’
 1214 |         lua_pushboolean(ls, ch->m_inspector->is_print_container_data());
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~
/tmp/guix-build-sysdig-0.40.1.drv-0/source/userspace/sinspui/cursesui.cpp:159:28: error: ‘container_info’ was not declared in this scope
  159 |                         if(container_info)
      |                            ^~~~~~~~~~~~~~
make[2]: *** [userspace/sysdig/CMakeFiles/csysdig.dir/build.make:166: userspace/sysdig/CMakeFiles/csysdig.dir/__/sinspui/cursescomponents.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [userspace/sysdig/CMakeFiles/sysdig.dir/build.make:152: userspace/sysdig/CMakeFiles/sysdig.dir/__/chisel/chisel_api.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [userspace/sysdig/CMakeFiles/csysdig.dir/build.make:82: userspace/sysdig/CMakeFiles/csysdig.dir/csysdig.cpp.o] Error 1
make[2]: *** [userspace/sysdig/CMakeFiles/sysdig.dir/build.make:82: userspace/sysdig/CMakeFiles/sysdig.dir/sysdig.cpp.o] Error 1
make[2]: *** [userspace/sysdig/CMakeFiles/csysdig.dir/build.make:222: userspace/sysdig/CMakeFiles/csysdig.dir/__/chisel/chisel_api.cpp.o] Error 1
make[2]: *** [userspace/sysdig/CMakeFiles/csysdig.dir/build.make:208: userspace/sysdig/CMakeFiles/csysdig.dir/__/sinspui/cursesui.cpp.o] Error 1
make[2]: Leaving directory '/tmp/guix-build-sysdig-0.40.1.drv-0/build'
make[1]: *** [CMakeFiles/Makefile2:223: userspace/sysdig/CMakeFiles/sysdig.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/tmp/guix-build-sysdig-0.40.1.drv-0/build'
make[1]: *** [CMakeFiles/Makefile2:255: userspace/sysdig/CMakeFiles/csysdig.dir/all] Error 2
make[1]: Leaving directory '/tmp/guix-build-sysdig-0.40.1.drv-0/build'
make: *** [Makefile:159: all] Error 2

error: in phase 'build': uncaught exception:
%exception #<&invoke-error program: "cmake" arguments: ("--build" "." "-j" "32" "--" "-l" "32") exit-status: 2 term-signal: #f stop-signal: #f> 
phase `build' failed after 5.3 seconds
command "cmake" "--build" "." "-j" "32" "--" "-l" "32" failed with status 2
build process 18 exited with status 256
builder for `/gnu/store/rrivpfq7jk2wi77i90819azplr28hgnj-sysdig-0.40.1.drv' failed with exit code 1
build of /gnu/store/rrivpfq7jk2wi77i90819azplr28hgnj-sysdig-0.40.1.drv failed
View build log at '/var/log/guix/drvs/rr/ivpfq7jk2wi77i90819azplr28hgnj-sysdig-0.40.1.drv'.
guix build: error: build of `/gnu/store/rrivpfq7jk2wi77i90819azplr28hgnj-sysdig-0.40.1.drv' failed
```

The inputs used for the build are:
```
dependencies: falcosecurity-libs@0.22.2 luajit@v2.1-0.04dca79 ncurses@6.2.20210619 nlohmann-json@3.12.0
+ pkg-config@0.29.2 yaml-cpp@0.8.0-0.2f86d13 zlib@1.3.1
```

Using the latest falcosecurity-libs commit produces similar errors, too.

**Comment by devZer0** [comment]
i also have this problem with ubuntu 25.10

**Comment by adibCynet** [comment]
I'm also trying to manually compile sysdig (`master`) with latest `falcosecurity-libs` and I'm getting the same issue of compilation errors around `sinsp`.

Did anyone find a solution?



This is the relevant section of error I see in my compilation:
```[491/524] Building CXX object userspace/sysdig/CMakeFiles/sysdig.dir/sysdig.cpp.o
FAILED: userspace/sysdig/CMakeFiles/sysdig.dir/sysdig.cpp.o
/usr/bin/c++ -DCHISEL_TOOL_LIBRARY_NAME=\"sysdig\" -DHAS_CAPTURE -DHAS_MODERN_BPF -DPLATFORM_NAME=\"Linux\" -DSYSDIG_PROBE_BPF_FILEPATH=\".scap/scap-bpf.o\" -DYAML_CPP_STATIC_DEFINE -D_GNU_SOURCE -I/root/manual_sysdig_build/sysdig_repo/build_try2/uthash-prefix/src/uthash/src -I/root/manual_sysdig_build/sysdig_repo/build_try2/tbb-prefix/src/tbb/include -I/root/manual_sysdig_build/sysdig_repo/build_try2/jsoncpp-prefix/src/include -I/root/manual_sysdig_build/sysdig_repo/build_try2/valijson-prefix/src/valijson/include -I/root/manual_sysdig_build/sysdig_repo/build_try2/re2-prefix/src/re2/include -I/root/manual_sysdig_build/sysdig_repo/build_try2/ncurses-prefix/src/ncurses/include -I/root/manual_sysdig_build/sysdig_repo/build_try2/zlib-prefix/src/zlib -I/root/manual_sysdig_build/sysdig_repo/build_try2/luajit-prefix/src/luajit/src -I/root/manual_sysdig_build/sysdig_repo/build_try2/userspace/sinspui -I/root/manual_sysdig_build/sysdig_repo/sysdig/userspace/sysdig/../sinspui -I/root/manual_sysdig_build/sysdig_repo/build_try2/userspace/sysdig -I/root/manual_sysdig_build/sysdig_repo/sysdig/userspace/sysdig/. -I/root/manual_sysdig_build/sysdig_repo/build_try2/njson-prefix/src/njson/single_include -I/root/manual_sysdig_build/sysdig_repo/sysdig/userspace/sysdig/../chisel -I/root/manual_sysdig_build/sysdig_repo/sysdig/userspace/sysdig/.. -I/root/manual_sysdig_build/sysdig_repo/build_try2/driver/src -I/root/manual_sysdig_build/falco_repo/libs/userspace/libsinsp -I/root/manual_sysdig_build/falco_repo/libs/userspace -I/root/manual_sysdig_build/falco_repo/libs/userspace/libscap -I/root/manual_sysdig_build/sysdig_repo/build_try2/libscap -I/root/manual_sysdig_build/falco_repo/libs -I/root/manual_sysdig_build/sysdig_repo/build_try2 -I/root/manual_sysdig_build/falco_repo/libs/userspace/libscap/linux -I/root/manual_sysdig_build/falco_repo/libs/userspace/libscap/engine/noop -I/root/manual_sysdig_build/sysdig_repo/build_try2/_deps/yamlcpp-src/include -Wall -ggdb   -std=c++17 -O3 -fno-strict-aliasing -DNDEBUG -MD -MT userspace/sysdig/CMakeFiles/sysdig.dir/sysdig.cpp.o -MF userspace/sysdig/CMakeFiles/sysdig.dir/sysdig.cpp.o.d -o userspace/sysdig/CMakeFiles/sysdig.dir/sysdig.cpp.o -c /root/manual_sysdig_build/sysdig_repo/sysdig/userspace/sysdig/sysdig.cpp
/root/manual_sysdig_build/sysdig_repo/sysdig/userspace/sysdig/sysdig.cpp: In function ‘captureinfo do_inspect(sinsp*, sinsp_cycledumper*, uint64_t, uint64_t, bool, bool, bool, bool, bool, std::unique_ptr<sinsp_filter>, std::vector<summary_table_entry>&, sinsp_evt_formatter*, sinsp_evt_formatter*)’:
/root/manual_sysdig_build/sysdig_repo/sysdig/userspace/sysdig/sysdig.cpp:889:76: error: ‘const class sinsp_evt_param’ has no member named ‘m_val’
  889 |                                         uint16_t id = *(int16_t *)parinfo->m_val;
      |                                                                            ^~~~~
/root/manual_sysdig_build/sysdig_repo/sysdig/userspace/sysdig/sysdig.cpp:895:76: error: ‘const class sinsp_evt_param’ has no member named ‘m_val’
  895 |                                         uint16_t id = *(int16_t *)parinfo->m_val;
      |                                                                            ^~~~~
/root/manual_sysdig_build/sysdig_repo/sysdig/userspace/sysdig/sysdig.cpp: In function ‘sysdig_init_res sysdig_init(int, char**)’:
/root/manual_sysdig_build/sysdig_repo/sysdig/userspace/sysdig/sysdig.cpp:1403:60: error: ‘class sinsp’ has no member named ‘set_print_container_data’
 1403 |                                                 inspector->set_print_container_data(true);
      |                                                            ^~~~~~~~~~~~~~~~~~~~~~~~
/root/manual_sysdig_build/sysdig_repo/sysdig/userspace/sysdig/sysdig.cpp:1413:60: error: ‘class sinsp’ has no member named ‘set_print_container_data’
 1413 |                                                 inspector->set_print_container_data(true);
      |                                                            ^~~~~~~~~~~~~~~~~~~~~~~~
/root/manual_sysdig_build/sysdig_repo/sysdig/userspace/sysdig/sysdig.cpp:1423:60: error: ‘class sinsp’ has no member named ‘set_print_container_data’
 1423 |                                                 inspector->set_print_container_data(true);
      |                                                            ^~~~~~~~~~~~~~~~~~~~~~~~
/root/manual_sysdig_build/sysdig_repo/sysdig/userspace/sysdig/sysdig.cpp:1585:60: error: ‘class sinsp’ has no member named ‘set_cri_timeout’; did you mean ‘set_thread_timeout_s’?
 1585 |                                                 inspector->set_cri_timeout(sinsp_numparser::parsed64(optarg));
      |                                                            ^~~~~~~~~~~~~~~
      |                                                            set_thread_timeout_s
/root/manual_sysdig_build/sysdig_repo/sysdig/userspace/sysdig/sysdig.cpp:1733:36: error: ‘class sinsp’ has no member named ‘set_cri_socket_path’
 1733 |                         inspector->set_cri_socket_path(cri_socket_path);
      |                                    ^~~~~~~~~~~~~~~~~~~
```

**Comment by therealbobo** [comment]
👋 quite a lot of things changed in falcosecurity/libs lately. I have this PR in-flight https://github.com/draios/sysdig/pull/2164 that should at least solve the 6.13 issue. For the 6.15 I'm afraid we'll have to wait the next libs release.

**Comment by therealbobo** [comment]
This should be fixed by the latest release.

**Comment by apteryks** [comment]
> This should be fixed by the latest release.

I'm still getting these errors:
```
/tmp/guix-build-sysdig-0.41.2.drv-0/source/userspace/sinspui/cursescomponents.cpp: In member function ‘const char* spy_text_renderer::process_event_spy(sinsp_evt*, int64_t*)’:
/tmp/guix-build-sysdig-0.41.2.drv-0/source/userspace/sinspui/cursescomponents.cpp:134:36: error: ‘const class sinsp_evt_param’ has no member named ‘m_val’
  134 |         *len = *(int64_t*)parinfo->m_val;
      |                                    ^~~~~
/tmp/guix-build-sysdig-0.41.2.drv-0/source/userspace/sysdig/sysdig.cpp: In function ‘captureinfo do_inspect(sinsp*, sinsp_cycledumper*, uint64_t, uint64_t, bool, bool, bool, bool, bool, std::unique_ptr<sinsp_filter>, std::vector<summary_:
/tmp/guix-build-sysdig-0.41.2.drv-0/source/userspace/sysdig/sysdig.cpp:849:76: error: ‘const class sinsp_evt_param’ has no member named ‘m_val’
  849 |                                         uint16_t id = *(int16_t *)parinfo->m_val;
      |                                                                            ^~~~~
/tmp/guix-build-sysdig-0.41.2.drv-0/source/userspace/sysdig/sysdig.cpp:855:76: error: ‘const class sinsp_evt_param’ has no member named ‘m_val’
  855 |                                         uint16_t id = *(int16_t *)parinfo->m_val;
      |                                                                            ^~~~~
/tmp/guix-build-sysdig-0.41.2.drv-0/source/userspace/chisel/chisel_api.cpp: In static member function ‘static int lua_cbacks::is_print_container_data(lua_State*)’:
/tmp/guix-build-sysdig-0.41.2.drv-0/source/userspace/chisel/chisel_api.cpp:1235:23: warning: unused variable ‘ch’ [-Wunused-variable]
 1235 |         sinsp_chisel* ch = (sinsp_chisel*)lua_touserdata(ls, -1);
      |                       ^~
make[2]: *** [userspace/sysdig/CMakeFiles/csysdig.dir/build.make:166: userspace/sysdig/CMakeFiles/csysdig.dir/__/sinspui/cursescomponents.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/tmp/guix-build-sysdig-0.41.2.drv-0/source/userspace/chisel/chisel_api.cpp: In static member function ‘static int lua_cbacks::is_print_container_data(lua_State*)’:
/tmp/guix-build-sysdig-0.41.2.drv-0/source/userspace/chisel/chisel_api.cpp:1235:23: warning: unused variable ‘ch’ [-Wunused-variable]
 1235 |         sinsp_chisel* ch = (sinsp_chisel*)lua_touserdata(ls, -1);
      |                       ^~

```

Using sysdig 0.41.2 and falcosecurity-libs 0.22.2.

**Comment by therealbobo** [comment]
I see, you are trying to compile it against 0.22.2. We'll try to tackle that on the next minor release.

**Comment by devZer0** [comment]
for me, installing sysdig 0.41.2 works and scap 8.1.0+driver works on ubuntu 25.10 with kernel 6.17
