### ISSUE TITLE
Sysdig fails to run on linux kernels with unified cgroups enabled

### ISSUE THREAD

**Issue by bluestealth** [draios/sysdig#806]
If cgroup-v2 is enabled sysdig will fail with the error message, "error creating the process list. Make sure you have root credentials." I have included a patch that works around the issue below. So far I only know this affects Arch Linux testing, and Fedora 26 Alpha.

[0001-Fix-for-linux-kernels-with-cgroup-v2-API-enabled.patch.txt](https://github.com/draios/sysdig/files/909689/0001-Fix-for-linux-kernels-with-cgroup-v2-API-enabled.patch.txt)

**Comment by Mic92** [comment]
Patch tested on nixos.

**Comment by mtorromeo** [comment]
It has been fixed by 2044108ef1f863f77735aa05ccd930ed462aa09c

**Comment by bluestealth** [comment]
Fix works for me, thanks for updating the PKGBUILD.

**Comment by syg00** [comment]
I'm still getting this on a newly built F26 - using sysdig-0-16.0-1
Was ok on F25 prior to the rebuild to F26

**Comment by Mic92** [comment]
Your version does not include the patch, it is not included in 0.16. Ask your maintainers to apply it manually since their was no new sysdig version since then.

**Comment by Mic92** [comment]
Your version does not include the patch, it is not included in 0.16. Ask your maintainers to apply it manually since their was no new sysdig version since then.

**Comment by luca3m** [comment]
Yes, it will go out soon

**Comment by syg00** [comment]
Ah sorry, figured as it was closed it would have shipped. I checked the "latest packages" link, but it had 15.0
I might pull the patch. Thanks all.
